# 服务器运行的端口，默认 8080
server.port=8081

# 数据库连接设置
# 使用环境变量，如果没有配置则默认使用本地数据库 (127.0.0.1:3306)
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/health_guardian?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
# MySQL 用户名，优先读取环境变量 DB_USER
spring.datasource.username=${DB_USER:root}
# MySQL 密码，优先读取环境变量 DB_PASS
spring.datasource.password=${DB_PASS:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 开启 SQL 打印日志，这样你在控制台就能看到程序到底对数据库做了什么
logging.level.org.springframework.jdbc.core.JdbcTemplate=info